 𝘴𝘶𝘥𝘰 𝘵𝘦𝘦 /𝘦𝘵𝘤/𝘢𝘱𝘵/𝘴𝘰𝘶𝘳𝘤𝘦𝘴.𝘭𝘪𝘴𝘵.𝘥/𝘨𝘪𝘵𝘩𝘶𝘣-𝘤𝘭𝘪.𝘭𝘪𝘴𝘵 > /𝘥𝘦𝘷/𝘯𝘶𝘭𝘭 \
        && 𝘴𝘶𝘥𝘰 𝘢𝘱𝘵 𝘶𝘱𝘥𝘢𝘵𝘦 \
        && 𝘴𝘶𝘥𝘰 𝘢𝘱𝘵 𝘪𝘯𝘴𝘵𝘢𝘭𝘭 𝘨𝘩 -𝘺

    - 𝘯𝘢𝘮𝘦: 𝘊𝘭𝘰𝘯𝘪𝘯𝘨 𝘙𝘖𝘔 𝘋𝘶𝘮𝘱 
      𝘪𝘥: 𝘤𝘭𝘰𝘯𝘦-𝘥𝘶𝘮𝘱
      𝘳𝘶𝘯: mp=$(pwd)
        python3 -m aospdtgen $working_dump
        echo "Successful!"
        mv $working_dump/output /home/LOS-Generator

    - name: Setting up Git
      id: setting-up-git
      run: |
        git config --global user.name "${{ env.GN }}"
        git config --global user.email "${{ env.GE }}"

    - name: Upload LineageOS Tree for GitHub
      id: upload-to-gh
      run: |
        cd /home/LOS-Generator/output
        git init
        git branch -M lineage-${{ env.CN }}
        git add .
        git commit -s -m "${{ env.CN }}: LineageOS compatible device tree"
        gh repo create lineage_device_${{ env.DB }}_${{ env.CN }} --public --description="LineageOS compatible device tree for ${{ env.CN }}." --source=. --remote=origin --push
        echo "Successful!"